physical_quantity = {
    'VELOCITY': 'Скорость',
    'HEAT_DROP': 'Теплоперепад',
    'TEMPERATURE': 'Температура',
    'PRESSURE': 'Давление',
    'MASS': 'Масса',
    'CONSUMPTION': 'Расход',
    'HEIGHT': 'Высота',
    'ROTATION_VELOCITY': 'Скорость вращения',
    'VOLTAGE': 'Напряжение',
    'CURRENT': 'Ток',
    'RESISTANCE': 'Сопротивление',
    'ACTIVE_POWER': 'Активная мощность',
    'REACTIVE_POWER': 'Реактивная мощность',
    'FREQUENCY': 'Частота',
    'ANGLE': 'Угол',
    'PERCENTAGE': 'Процент',
    'VIBRATION_VELOCITY': 'Виброскорость',
    'VIBRATION_DISPLACEMENT': 'Виброперемещение',
    'AXIAL_SHIFT': 'Осевой сдвиг',
    'CONCENTRATION': 'Концентрация (газов)',
    'HEAT_RATE': 'Удельный расход теплоты',
    'FUEL_RATE': 'Удельный расход топлива',
    'HEAT_VALUE': 'Теплота сгорания',
    'HEAT_CAPACITY': 'Теплоемкость',
    'TIME': 'Время',
    'VOLUME': 'Объем',
    'DENSITY': 'Плотность',
    'VOLUME_FLOW_RATE': 'Объёмный расход'
}

